name: Demo

on:
  push:
    branches: [ production, staging ]

jobs:
  branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
    steps:
    - name: branch
      id: branch
      run: echo "::set-output name=branch::${GITHUB_REF##*/}"

  build_deploy:
    runs-on: ubuntu-latest
    needs: [ branch ]
    strategy:
      matrix:
        serviceName: [ service1, service2 ]
    environment: 
     name: ${{ needs.branch.outputs.branch }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: login
      run: echo docker login
    - name: build
      working-directory: ${{ matrix.serviceName }}
      run: |
        pwd
        echo docker build ${{ matrix.serviceName }} ${{ secrets.ACR_NAME }}
        echo docker push
    - name: deploy
      working-directory: ${{ matrix.serviceName }}
      run: |
        echo helm upgrade ${{ matrix.serviceName }}
