name: Demo

on:
  push:
    branches: [ production, staging ]
  workflow_dispatch:
  
jobs:
  branch:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
    steps:
    - name: branch
      id: branch
      run: echo "::set-output name=branch::${GITHUB_REF##*/}"

  build_deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [ branch ]
    strategy:
      matrix:
        serviceName: [ service1, service2 ]
    environment: 
     name: ${{ needs.branch.outputs.branch }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: login
      run: echo docker login
    - name: build
      working-directory: ${{ matrix.serviceName }}
      run: |
        pwd
        echo docker build ${{ matrix.serviceName }} ${{ secrets.ACR_NAME }}
        echo docker push
    - name: build-extra
      working-directory: ${{ matrix.serviceName }}
      run: |
        echo extra steps for only one service
      if: ${{ matrix.serviceName == 'service2' }}
    - name: deploy
      working-directory: ${{ matrix.serviceName }}
      run: |
        echo helm upgrade ${{ matrix.serviceName }}
        
  stop:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
    - name: stop
      run: echo stop process
